In [ ]:
"""All Numpy problems
"""

In [ ]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array

In [2]:
import numpy as np

arr = np.array([12.23, 13.32, 100, 36.32])
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
a=[2,3,4]
b=[5,6,7]
c=[8,9,10]

arr = np.array([a,b,c])
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [4]:
arr = np.zeros(10)
print(arr)
arr[6] = 11
print("Updated 6th value to 11 : ")
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated 6th value to 11 : 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [5]:
arr = np.arange(12,38)
print("Original Array : ")
print(arr)
print("Reverse Array : ")
print(arr[::-1])

Original Array : 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array : 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [16]:
arr = np.ones([5,5])
print("Original Array : ")
print(arr)
print("\nExpected Ouput : ")
print(arr)

Original Array : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Expected Ouput : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [17]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
print("0 on the border and 1 inside in the array")
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
arr = np.zeros((8,8))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


8. Write a Python program to convert a list and tuple into arrays.

In [9]:
list = [1,2,3,4,5,6,7,8]
tuple_ele = ([8,4,6],[1,2,3])
list_to_arr = np.array(list)
tuple_to_arr = np.array(tuple_ele)
print("List to array : \n")
print(list_to_arr)
print("\nTuple to array : \n")
print(tuple_to_arr)

List to array : 

[1 2 3 4 5 6 7 8]

Tuple to array : 

[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array

In [10]:
arr = np.array([10,20,30])
print("Old Array : ")
print(arr)
arr2 = np.array([30,40,50,60,70,80,90])
new_arr = np.append(arr , arr2)
print("New Array : ")
print(new_arr)

Old Array : 
[10 20 30]
New Array : 
[10 20 30 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.


In [11]:
complex_list =  [1.00000000 + 0.j , 0.70710678 + 0.70710678j]
comple_arr = np.array(complex_list)
real_arr = []
img_arr = []
for i in comple_arr:
    real_arr.append(i.real)
    img_arr.append(i.imag)
print("Real part of Array : ")
print(np.array(real_arr))
print("Imaginary part of Array : ")
print(np.array(img_arr))

Real part of Array : 
[1.         0.70710678]
Imaginary part of Array : 
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.


In [12]:
arr = np.array([1,2,3])
print(f"Size of the array : {arr.size}")
print(f"Length of one array element in bytes : {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array : {arr.nbytes}")

Size of the array : 3
Length of one array element in bytes : 4
Total bytes consumed by the elements of the array : 12


12. Write a Python program to find common values between two arrays.

In [13]:
arr1 =  np.array([0,10,20,40,60])
arr2 = [10, 30, 40]

common_ele = np.intersect1d(arr1,arr2)
print(f"Common element between {arr1} and {arr2} are : {common_ele}")

Common element between [ 0 10 20 40 60] and [10, 30, 40] are : [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2

In [14]:
arr1 =  np.array([ 0, 10, 20, 40, 60, 80 ])
arr2 = np.array([10, 30, 40, 50, 70])

diff_arr = np.setdiff1d(arr1,arr2)
print(f"Set difference between {arr1} and {arr2} are : {diff_arr}")

Set difference between [ 0 10 20 40 60 80] and [10 30 40 50 70] are : [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays

In [15]:
arr1 =  np.array([ 0, 10, 20, 40, 60, 80 ])
arr2 = np.array([10, 30, 40, 50, 70])

diff_arr = np.setxor1d(arr1,arr2)
print(f"Set exclusive or between {arr1} and {arr2} are : {diff_arr}")

Set exclusive or between [ 0 10 20 40 60 80] and [10 30 40 50 70] are : [ 0 20 30 50 60 70 80]
